scripts/kernel_lib.py: fix get_kernel_sru_cycle search for LP task
 LP API searchTasks() method can return multiple results that we are not
 interested and that would raise an error, like searching for
 "linux: 4.4.0-250.284" can return other kernels as well, like below:

    found multiple (2) results:
     trusty/linux-lts-xenial: 4.4.0-250.284~14.04.1 -proposed tracker
     xenial/linux: 4.4.0-250.284 -proposed tracker
    Traceback (most recent call last):
    File "/home/ubuntu-security/git-pulls/ubuntu-cve-tracker/scripts/kernel-abi-check", line 335, in <module>
        if not pocket_abis_match(release, srcs, meta, signed):
    File "/home/ubuntu-security/git-pulls/ubuntu-cve-tracker/scripts/kernel-abi-check", line 224, in pocket_abis_match
        print("USN needed: %s/%s (last USN: %s) - cycle: %s" % (release, kernel_title, last_usn, get_kernel_sru_cycle(kernel_title, lp)), file=sys.stderr)
    File "/home/ubuntu-security/git-pulls/ubuntu-cve-tracker/scripts/kernel_lib.py", line 33, in get_kernel_sru_cycle
        raise ValueError('More than one task with title %s found' % (kernel_title))
    ValueError: More than one task with title linux: 4.4.0-250.284 found

 instead we can narrow down the search based on the text we want by
 matching with the bug title.
 also, we may not want to see errors as the search for the cycle is not
 really what we want from this, so it would be better to just skip it
 instead of blocking the whole execution. So, I've moved the error
 message to a debug message, if desired.

Signed-off-by: Rodrigo Figueiredo Zaiden <rodrigo.zaiden@canonical.com>